{% set version = "0.7.10" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-qdapregex
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/qdapRegex_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/qdapRegex/qdapRegex_{{ version }}.tar.gz
  sha256: b03de838f089b352a0c49d6eaa9b36ba47333c36615d20960f0ac3535f82df88

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-stringi >=0.5_5
  run:
    - r-base
    - r-stringi >=0.5_5

test:
  commands:
    - $R -e "library('qdapRegex')"           # [not win]
    - "\"%R%\" -e \"library('qdapRegex')\""  # [win]

about:
  home: http://trinker.github.com/qdapRegex/
  license: GPL-2.0-only
  summary: A collection of regular expression tools associated with the 'qdap' package that may be useful outside of the context of discourse analysis. Tools include removal/extraction/replacement of abbreviations, dates, dollar amounts, email addresses, hash tags, numbers, percentages, citations, person tags, phone numbers,
    times, and zip codes.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - CurtLH
