{% set version = '0.7.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-qdapregex
  version: {{ version|replace("-", "_") }}

source:
  fn: qdapRegex_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/qdapRegex_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/qdapRegex/qdapRegex_{{ version }}.tar.gz
  sha256: 377d77e975b12593e8a38689664d80641946721fbb0e287353f20daf78c048f5

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1003
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-stringi >=0.5_5
  run:
    - r-base
    - r-stringi >=0.5_5

test:
  commands:
    - $R -e "library('qdapRegex')"           # [not win]
    - "\"%R%\" -e \"library('qdapRegex')\""  # [win]

about:
  home: http://trinker.github.com/qdapRegex/
  license: GPL-2
  summary: A collection of regular expression tools associated with the 'qdap' package that may
    be useful outside of the context of discourse analysis. Tools include removal/extraction/replacement
    of abbreviations, dates, dollar amounts, email addresses, hash tags, numbers, percentages,
    citations, person tags, phone numbers, times, and zip codes.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - CurtLH
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
