travis:
  secure:
    BINSTAR_TOKEN: N0eS6RdoiHEfqW/tEfZgVhlombgodVWmcm5QGgVoOvh5ehG8jWgdqXTpyVzfH9nTvIOI7epq+t2e9TTTuP7QamSruRMPTAPIpMQImFJ08tHBFBbLFQInQhBqO2taXqL2SxURXYQt5lTM32l8vuBeMQeK75N6ko1GgjxNYGa3ZilFQFVDBLLh1G1yLHtPZ6PlTgLAiPteKXJRFKLNQjmld7DrjQFpefaWeNbVU8/7tqFNsshSrhRIzmjp4wCKCpXgyCq/kKL+oORQcKWLbaQtbubMc+uacnH/0MA8OIV6ETaOBhNdbUOUVg15DKLYuT25cMwcPnLqiiLfc9Ye7FLeXPEpnAtUTGk7JafSlsnE1MP6sbYUpp8CqlW074CA6gakUrrZXeEaM4ANeGDFh8qfsFXYJXS5nWJpopS609BlUNOg+7kDfysYcZKUOaNIGcJZpUMsR93oDpVqyt36iQmnNr70tm59tctHK2cn4lr4jCH2/ZYJQ2jDUQPpHnbj7eysc+YMkWkJc7/HScraNbUlwf8NuhhsCN0UOhEXkjli1Gyx039Y8/yUCWQV/bPhHlP7MVZgn1Xn1mI2q/8r2kilOIqQS1WmLvXB2bSyjPCB1QqX70kCweCIj5TEd+3IHm+IA7mgclEp7Z2mRE+jZZRNsrbd1R+6bYLCEDDQzkJFmKc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
