travis:
  secure:
    BINSTAR_TOKEN: cF2YFalSuA2xUv+UC+mHY7aZSitsTGOiBUM9tqgunWXsCArNrkE0NQZ1hAPHc5Ch3ONQNg8CxS/Pkx1mcoxTXLe1MVIXbfuGColxJmiKCG+ufccNi699SbazEVHJ5HtR7B6S+rmK/EmzNmtZDEsonul3QXgvnRwSuquav9hZxkUWa9cE7jIO6df5iIOizzK+FnsTXyCSWcCDQx62xcp33Oed2ffN4gaFlTKGUhLuHejXzFy38BwBeNyinnBCLVHvAouCT4vn/FraZNjeUSiDlNVIfL7Ass+sua3y11yRsD5CdBMKbO9VPAKE/T4b6uYuqJHZwWskyly/S2fR9bJnViysICKZkhFCMAdOJ0FD+mReOR92gGrC8k7w0wk2ECpMo82r7lm7pLksiMEb1w49qRnNkTHLVSI+voYONW+MQvCEGuPt4UE57vpbq0jdydNB4qTIJKO41xXWORy7mMgAFyAiw1pMdi+5ushzuj/VbYo/10CfxVjchx6lxN8R6ZtBxwhYpvTLwWi7W3P/rmkj0jgHo6JVoAYUgi9+PCEEvWqiu+3O1FVrY7EIvCY9jMkxWzbyetwtZLKzjvo1QhX83F0G63uzAwBJEkW3DSw728/4QTSGfHOGkNtUmsxAwud2Qqo5S9F43WXohdRW8sIOfAC12QxwpTxVofmsCi5xCEk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
